package-lock.json
package.json
src/core/assets/generators/tests/asset.generator.spec.ts
src/lib/command-descriptors/serve.command-descriptor.ts
src/lib/command-descriptors/tests/serve.command-descriptor.spec.ts
src/lib/handlers/serve-command.handler.ts
src/lib/handlers/tests/serve-command.handler.spec.ts
src/nest-cli.application.ts

This PR implements a `nest serve` command into the Nest CLI. It is compatible both with TypeScript and JS, and is based on Nodemon.
To make this work, though, the starter projects need to be updated. Primarily, just add the `entryFile` property to `nestconfig.json`; this property should point to the main server file for Nodemon to execute.
Enjoy!

feat(cli): add serve command

---

README.md

Also leaves the fireplace better by adding line returns between list because some markdown processor needs it in order to display lists correctly.
Fix #25.

Add serve command to the readme, fix #25

---

package-lock.json
package.json
src/common/program/interfaces/command.handler.interface.ts
src/core/utils/nest-ascii.ts
src/lib/command-descriptors/info.command-descriptor.ts
src/lib/command-descriptors/tests/info.command-descriptor.spec.ts
src/lib/handlers/info-command.handler.ts
src/lib/handlers/tests/info-command.handler.spec.ts
src/nest-cli.application.ts

This command will help Nest consumers get their environment info out faster to paste into new issues to help contributors diagnose faster.
Usage: `nest info`
Alias: `nest i`
Sample logs: 
This issue closes #27

Add Info Command

---

lib/runners/abstract.runner.ts

fix() : wrap runner binary with quotes to manage spaces in binary path

---

actions/new.action.ts
commands/generate.command.ts
commands/new.command.ts
commands/update.command.ts
lib/inputs/parse.ts
test/lib/inputs/parse.spec.ts

Hi there.
I noticed that `--skip-install` did not seem to work in the `sprint-1` branch. I fixed this in `new.action.ts`. Another part of the fix is in `new.command.ts` where the property `skip-install` was read in `command`, instead of `skipInstall`. 
_NB: At the same time I took the liberty to remove the `parse` utility method which was adding more complexity than required for the creation of a simple literal object (`Input`). Let me know if I shouldn't have_ 
Starting from this point, I'd like to define a factory (or any other soft abstraction) for `*.command.ts`s and remove the sort-of duplications (filling `inputs` and `options`). If you think this is appropriate/relevant.

fix(new): --skip-install never working (sprint-1)

---

actions/new.action.ts

Fix for #138 and #148. If a non-kebab-case project name was passed to `nest new` it would fail due to a directory name mismatch.

fix(new): format install directory to match schematic directory

---

lib/package-managers/abstract.package-manager.ts

* Using **test_p** as the project name and then I got below error:
```shell
➜  Projects nest new test_p
⚡️  Creating your Nest project...
🙌  We have to collect additional information:
? description : a test project
? version : 0.0.0
? author : sanhan.sj
💥  Thank you for your time!
CREATE /test-p/.prettierrc (51 bytes)
....
CREATE /test-p/webpack.config.js (695 bytes)
? Which package manager would you ❤️  to use? npm
▹▹▹▹▹ Take ☕️  or 🍺  during the packages installation process and enjoy your timeevents.js:183
throw er; // Unhandled 'error' event
^
Error: spawn /bin/sh ENOENT
at _errnoException (util.js:1022:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
at onErrorNT (internal/child_process.js:372:16)
at _combinedTickCallback …
```

Fixed: Create project crash

---

lib/configuration/defaults.ts
lib/configuration/nest-configuration.loader.ts
lib/readers/file-system.reader.ts
lib/readers/reader.ts
test/lib/configuration/nest-configuration.loader.spec.ts

Supports:
1. nest-cli.json
2. nestcli.json
otherwise, loads default options.
resolves: #174

refactor: use nest-cli.json (backward compatible + defaults)

---

README.md

A `-` is missing in the `--rm` option 😄

Fix Docker run command typo

---

Dockerfile
README.md

Run `npm run build` before execute npm link also updated docker and readme file.

fix: run npm build before run npm link

---

lib/ui/messages.ts

I removed a double space in the 
> Which package manager would you :heart: to use?
message that is shown upon initialization of a new project.
Other strings in the file also contained double spaces after emojies, but the emoji was at the beginning of the string, so it might have been an intentional styling. I left them as they were before.

remove double-space in package manager question

---

.prettierrc
bin/nest.ts
commands/generate.command.ts
package.json
tools/gulp/gulpfile.ts

- Prettier: Preserve quotes
- package.json: Make tslint load the npm way
- nest.ts, generate.command.ts, gulpfile.ts: Prettier changes

Prettier and linter would differ in configuration

---

lib/runners/schematic.runner.ts
test/lib/runners/schematic.runner.spec.ts

Now working on Windows and with local nest-cli installations over npx.
- Changed finding logic: Now using the modules resolution system to test the usual require locations
- Changed tests: Now mocking existsSync by checking for rightPath

Make schematic runner more robust. 

---

lib/compiler/webpack-compiler.ts

- [y] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [y] Tests for the changes have been added (for bug fixes / features)
- [y] Docs have been added / updated (for bug fixes / features)
```
[y] Bugfix
[ ] Feature
```
When nest debug in docker with 
nest-cli.json
```json
{
"collection": "@nestjs/schematics",
"sourceRoot": "src",
"compilerOptions": {
"webpack": true
}
}
```
webpack.config.js
```js
const config = (option) => {
option.watch = true …
```

fix(cli): webpack in docker can't watch

---

actions/build.action.ts
actions/start.action.ts
commands/build.command.ts
commands/start.command.ts
lib/configuration/configuration.loader.ts
lib/configuration/nest-configuration.loader.ts
test/lib/configuration/nest-configuration.loader.spec.ts

- [ X ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ X ] Tests for the changes have been added (for bug fixes / features)
- [ X ] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ X ] Feature
```
Implements #452 
Both *build* and *start* commands now accept a --config option to switch between different nest-cli.config.json files.
Eg: `nest-cli build --config brand-new-config-file.nest-cli.json`
```
[ ] Yes
[ X ] No …
```

Adds --config option to build and start commands

---

.gitignore
README.md
actions/add.action.ts
actions/generate.action.ts
actions/info.action.ts
bin/nest.ts
commands/add.command.ts
commands/build.command.ts
commands/generate.command.ts
commands/info.command.ts
commands/new.command.ts
commands/start.command.ts
commands/update.command.ts
lib/package-managers/abstract.package-manager.ts
lib/ui/messages.ts
lib/utils/load-configuration.ts
lib/utils/project-utils.ts
package.json

```
[ ] Bugfix
[x] Feature
[x] Code style update (formatting, local variables)
```
See below
```
[ ] Yes
[x] No
But, see below
```
This PR introduces a new feature for the `nest add` command.  The command now:
- Allows passing in a project name with `-p` option
- Automatically handles multi-project selection if a project is not supplied
- checks for whether the project structure is *standard* or *monorepo*
- if monorepo, prompts for the project name
- Invokes the `nest-add` schematic on the target library and passes in the source root …

feat() support project selection in add action

---

actions/new.action.ts
commands/new.command.ts

nestjs/nest-cli#283
```
[ ] Bugfix
[x] Feature
```
Issue Number: nestjs/nest-cli#283
```
> nest new @scope/package
```
This command will generate application files inside the 'package' folder and additionally, it will put everything inside a wrapping folder '@scope'. Furthermore currently there is no option to generate the application to another directory than the same as the application name says.
```
> nest new @scope/package --directory=scope-package
```
This command will produce new application …

feat(cli): add directory option to the application schematic

---

actions/generate.action.ts
commands/command.input.ts
commands/generate.command.ts
lib/compiler/helpers/get-value-or-default.ts
lib/configuration/configuration.ts
lib/configuration/defaults.ts
lib/utils/project-utils.ts
test/lib/compiler/helpers/get-value-or-default.spec.ts
test/lib/configuration/nest-configuration.loader.spec.ts

```
[ ] Bugfix
[x] Feature
```
Currently you must specify `--no-spec` on *ALL* generate commands, to not pass the `--spec` flag onwards to the collection, that generates the files. No configuration is available to allow for the `--no-spec` command to be default behavior, unless otherwise specified.
This PR fixes/closes:
- #314 
With this feature, you are able to specify a `generateOptions` in the configuration file, which currently only have the ability to change the generation options for `spec`, …

feat(cli) Add generateOptions to configuration

---

lib/compiler/assets-manager.ts

```
[x ] Bugfix
[ ] Feature
```
assets will be copied to the default outDir of the app.
will be copied to the outDir of each item
```
"org-api": {
"type": "application",
"root": "apps/org-api",
"entryFile": "main",
"sourceRoot": "apps/org-api/src",
"compilerOptions": {
"tsConfigPath": "apps/org-api/tsconfig.app.json",
"assets": [{
"include": "../client/**/*",
"outDir": "dist/apps/org-api/apps/org-api/client/"
}]
}
}
```
```
[ ] Yes
[x] No
```

bugfix(cli) use outDir from asset item instead of the default one

---

actions/build.action.ts
commands/start.command.ts
lib/compiler/watch-compiler.ts

```
[ ] Bugfix
[x] Feature
```
Issue Number: #587 
There's no option for disable the console "clear" on `nest start` command.
Add option name `preserveWatchOutput` like `nest start --watch --preserveWatchOutput`.
It only works when watchmode is enabled and compiler is tsc.
```
[ ] Yes
[x] No
```

feat(cli) Add preserveWatchOutput option on start command

---

actions/start.action.ts
commands/start.command.ts

```
[ ] Bugfix
[X] Feature
```
Issue Number: https://github.com/nestjs/nest-cli/issues/592
New flag debug-brk to pass inspect-brk with port or by itself
```
[ ] Yes
[X] No
```

feat(cli): Added inspect-brk flag

---

actions/start.action.ts
commands/start.command.ts

Revert "feat(cli): Added inspect-brk flag"

---

lib/compiler/defaults/webpack-defaults.ts

Disable the type-checking while transpiling the TS files, as the ForkTsCheckerWebpackPlugin
is already handling this within another process
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
Run `nest build` for a webpack based Nest.js-CLI project (it should be considerably big). 
With ts-loaders `transpileOnly`-flag set to `true`, the transpilation process gets a serious speed up, as it disables the type-checking while transpiling the sources.
It is still safe to do this, as the type checking takes …

build: speed up the TypeScript transpilation when using webpack

---

lib/compiler/typescript-loader.ts

```
[ ] Bugfix
[x] Feature
```
Issue Number: #555 
Resolution of the Typescript binary no longer fails when using the CLI in a Yarn PnP environment.
```
[ ] Yes
[x] No
```
I'm not sure whether the `try/catch` is really necessary, but it does allow the custom error to be thrown instead of the `require` call itself erroring.

feat: Compatibility With Yarn PnP

---

lib/compiler/webpack-compiler.ts

- [-] Tests for the changes have been added (for bug fixes / features)
```
[x] Bugfix
[ ] Feature
```
The err object was not checked and it was relied on defined stats. This results in a confusing type error that has nothing to do with the actual error.
Issue Number: #868 
Now early exit when err object is set but stats remains undefined.
```
[ ] Yes
[x] No
```

fix(): fatal errors during build won't prompt (webpack)

---

lib/compiler/typescript-loader.ts

```
[ ] Bugfix
[ ] Feature
```
Issue Number: #885
The fix in #748 will incorrectly load the version installed with @nest/cli when using PnP. Additionally, hardcoding node_modules and searching for typescript within it can fail with yarn workspaces depending on hoisting layout, even without using PnP - or it can lead to unexpected results (wrong typescript version being found/used)
Use `require.resolve` to find `typescript`, and load it using `require`
A special case to handle Yarn PnP is no longer …

refactor: find typescript using `require.resolve`

---

actions/abstract.action.ts
lib/compiler/workspace-utils.ts

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Breaking changes in the Typescript 4.1.* related to async and promises.
```
Not changed.
Correcting "fix(deps): update dependency typescript to v4.1.3" #957 to successfully build nest-cli for v4.1.*
```
[ ] Yes
[x] No
```
See, https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#abstract-members-cant-be-marked-async and https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#resolves-parameters-are-no-longer-optional-in-promises …

fix(deps): Typescript 4.1  breaking changes

---

commands/new.command.ts

Following the docs for the --language option will result in:
https://github.com/nestjs/nest-cli/issues/1030. This change fixes the error by converting language
shortcodes to lowercase.
#1030
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1030 
The new behavior is the expected behavior as described in #1030.
```
[ ] Yes
[x] No
```
I did not see any tests for any of the commands, and so did not write a test for this bug. If I have overlooked those tests, would be happy to add a test for the language …

fix(@nestjs/cli): convert --language shortcode to lowercase

---

lib/compiler/hooks/tsconfig-paths.hook.ts

The current behaviour is that type only imports don't get removed if they contain a tsconfig alias.
Closes #1145
```
[X] Bugfix
[ ] Feature
```
Issue Number: #1145
Type only imports get removed if they contain a tsconfig path alias.
```
[ ] Yes
[X] No
```

fix: allow to remove type only imports including alias path

---

package-lock.json
package.json

`webpack@5` is now direct dependency of `@nestjs/cli` and it's pure TS (native) with it's own `.d.ts`.
Package `@types/webpback@5` is now direct passhtrough to `webpack` itself.
Thanks!
```
[ ] Yes
[x] No
```
You should be albe to better see possible impact, say when somehone is still using a mix of outdated deps and using Yarn resolution.
TL;DR;
`@types/webpack` is no longer required to be referenced rirectly, it's handled properly as you're on the `webpack@5`
lng:
The community around the TS and definitey typed is working on improving TS expeerience when using DefinitelyTyped definition, which was under huge impact after `webpack` migrated to native TS implementaion (which, huh, differs from DT definition, even if …

chore(deps): drop @types/webpack dependency

---

lib/configuration/configuration.ts

JSON Schema validation fails for nest-cli.json if an item in CompilerOptions.plugins[] uses the object notation.
- [✅] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [✅] Tests for the changes have been added (for bug fixes / features)
- [✅] Docs have been added / updated (for bug fixes / features)
I don't think tests or doc updates are applicable here. Backwards compatible as it just adds a union with the existing type `string[]` and does not affect the preferred default value. 
```
[ ] Bugfix
[ ] Feature
[ ] Build related …
```

docs(types) - update plugins configuration interface

---

actions/start.action.ts
lib/utils/tree-kill.ts

fix #1124 
```
[x] Bugfix
[ ] Feature
```
When running `nest start --watch`, edit `tsconfig.json`. It will report an error and exit.
running `nest start --watch` again, it will prompt that the `Error: listen EADDRINUSE: address already in use :::3000`
> Listener functions must only perform synchronous operations. The Node.js process will exit immediately after calling the 'exit' event listeners causing any additional work still queued in the event loop to be abandoned. In the following example, for …

fix: Application did not exit on watch process abnormal exit

---

actions/new.action.ts
lib/configuration/defaults.ts
lib/package-managers/index.ts
lib/package-managers/package-manager.factory.ts
lib/package-managers/package-manager.ts
lib/package-managers/pnpm.package-manager.ts
lib/runners/pnpm.runner.ts
lib/runners/runner.factory.ts
lib/runners/runner.ts
test/lib/package-managers/pnpm.package-manager.spec.ts

nest-cli only offers `npm` and `yarn` as package managers. As `pnpm` is growing rapidly into a third major player in the JavaScript package manager ecosystem, nest-cli should support it both when running `nest new` and throughout for running nest scripts and installing dependencies.
pnpm is now available as a package manager, like npm and yarn. Since pnpm uses the same commands [requires no significant changes](https://pnpm.js.org/en/pnpm-vs-npm) compared to working with npm, there are no substantial changes to codebase other than the addition of new objects/references for pnpm (and one logic change). pnpm passes all tests, including when using nest-cli to run the default app using …

feat(cli): add pnpm package manager support

---

lib/compiler/defaults/webpack-defaults.ts

```
[x] Bugfix
[ ] Feature
```
`afterDeclarations` with Webpack compilation won't work because it was spelled `afterDeclaratqions`
`afterDeclarations` with Webpack compilation should work
```
[ ] Yes
[x] No
```

fix(compiler): remove type in afterDeclarations property

---

CONTRIBUTING.md

remove the link referencing the missing developer.md file
resolves #1300
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: docs(contributing.md)
```
Issue Number: #1300 
The file doesn't refer to a missing `DEVELOPER.md` file anymore
```
[ ] Yes
[x] No
```

docs: remove missing link from contributing.md

---

commands/new.command.ts
package-lock.json
package.json
test/lib/schematics/schematic.option.spec.ts

```
[ ] Bugfix
[x] Feature
```
Issue Number: https://github.com/nestjs/schematics/issues/597
CLI users can use `nest new --strict` if they want to turn on TypeScript's strict mode in their projects from beginning, ie. the following TS compiler options will be `true` instead of the default `false`: `strictNullChecks`, `noImplicitAny`, `strictBindCallApply`, `forceConsistentCasingInFileNames` and `noFallthroughCasesInSwitch`
```
[ ] Yes
[x] No
```
I upgraded `@nestjs/schematics` dependency to `8.0.3` to …

feat(): add optional --strict flag on "nest new"

---

lib/package-managers/abstract.package-manager.ts
test/lib/package-managers/npm.package-manager.spec.ts
test/lib/package-managers/pnpm.package-manager.spec.ts
test/lib/package-managers/yarn.package-manager.spec.ts

```
[ ] Bugfix
[ ] Feature
[x Code style update (formatting, local variables)
```
```
[ ] Yes
[x] No
```

fix(doc): rename Developement to Development

---

lib/package-managers/abstract.package-manager.ts
lib/package-managers/npm.package-manager.ts
lib/package-managers/package-manager-commands.ts
lib/package-managers/pnpm.package-manager.ts
lib/package-managers/yarn.package-manager.ts
lib/runners/abstract.runner.ts
lib/ui/messages.ts
test/lib/package-managers/npm.package-manager.spec.ts
test/lib/package-managers/pnpm.package-manager.spec.ts
test/lib/package-managers/yarn.package-manager.spec.ts

```
[ ] Bugfix
[x] Feature
```
Issue Number: close #1499 
display this message instead (taking PNPM as example):
```
🙀  Packages installation failed!
In case you don't see any errors above, consider manually running the failed command pnpm install to see more details on why it errored out
```
Also, I've replaced the `--silent` of PNPM by [`--reporter=silent`](https://pnpm.io/pt/cli/install#--reportername) (v6)
```
[ ] Yes
[x] No
```
Instead of hard coding the full instalation command that might not be …

feat: better instructions on package manager installation failure

---

lib/compiler/hooks/tsconfig-paths.hook.ts
test/lib/compiler/hooks/__snapshots__/tsconfig-paths.hook.spec.ts.snap
test/lib/compiler/hooks/fixtures/aliased-imports/src/bar.tsx
test/lib/compiler/hooks/fixtures/aliased-imports/src/baz.js
test/lib/compiler/hooks/fixtures/aliased-imports/src/foo.ts
test/lib/compiler/hooks/fixtures/aliased-imports/src/main.ts
test/lib/compiler/hooks/fixtures/aliased-imports/src/qux.jsx
test/lib/compiler/hooks/tsconfig-paths.hook.spec.ts

```
[x] Bugfix
[ ] Feature
```
Commands like `nest start` and `nest build` replace the path of imports using path aliases with its relative path.   
But this currently fails for imports pointing to a `.tsx` or `jsx` file.
Issue Number: #1547
Path aliases are replaced not only for imports pointing to `.ts` and `.js` files, but for `.tsx` or `jsx` also.
```
[ ] Yes
[x] No
```

fix: replace aliased imports for tsx and jsx files

---

commands/new.command.ts

Prior to this change option defaults were not visible to a CLI user:
```
Options:
--directory [directory]                  Specify the destination directory
-d, --dry-run                            Report actions that would be performed without writing out results.
-g, --skip-git                           Skip git repository initialization.
-s, --skip-install                       Skip package installation.
-p, --package-manager [package-manager]  Specify package manager.
-l, --language [language]                Programming language to be used (TypeScript or JavaScript).
-c, --collection [collectionName]        Schematics collection to use.
--strict                                 Enables strict mode in TypeScript.
-h, --help                               Output usage information.
``` …

feat(core): show defaults in CLI output

---

actions/generate.action.ts
commands/generate.command.ts
lib/schematics/schematic.option.ts
test/lib/schematics/schematic.option.spec.ts

```
[ ] Bugfix
[x] Feature
```
When using the `generate` command you can skip the `service` `controller` automatic import into `module` by adding `--skip-import`
```
[ ] Yes
[x] No
```

feat: Add skip import option to generate command

---

CONTRIBUTING.md

```
[ ] Bugfix
[ ] Feature
```
Replace gitter by discord
```
[ ] Yes
[x] No
```

docs(contributing): replace gitter by discord

---

lib/configuration/defaults.ts
lib/utils/get-default-tsconfig-path.ts
test/lib/configuration/nest-configuration.loader.spec.ts
test/lib/utils/get-default-tsconfig-path.spec.ts

```
[ ] Bugfix
[x] Feature
```
Some simple and small project only use `tsconfig.json` and have no `tsconfig.build.json` on the root of project. It will throw an error if developer execute `nest build` on the root. They have to execute `nest build -p tsconfig.json`, which is not simple and clean. Moreover, some developer who is new to TypeScript only know `tsconfig.json` and don't know what is `tsconfig.build.json`.
Execute `nest build` will not throw error if there is only `tsconfig.json`.
```
[ ] Yes …
```

feat: tsconfig.json by default if tsconfig.build.json not exist

---

actions/generate.action.ts
lib/configuration/configuration.ts
lib/utils/project-utils.ts

```
[ ] Bugfix
[x] Feature
```
currently a user needs to pass a `--flat` flag every time desired when running a generate command
Issue Number: closes #1518
allows for `flat` to be set in generateOptions configuration. defaults to `false`
```json
{
"generateOptions": {
"flat": true
}
}
```
```
[ ] Yes
[x] No
```

feat(config): allow for flat generate option configuration

---

lib/package-managers/pnpm.package-manager.ts
test/lib/package-managers/pnpm.package-manager.spec.ts

pnpm v7.0.0 until 7.13.5 uses `--strict-peer-dependencies=true` which causes a failure when not all `peerDependencies` are installed. By setting the flag explicitly, this will no longer be a problem for new users.
fix: #1806
```
[X] Bugfix
[ ] Feature
```
When a user uses pnpm 7.0.0 to 7.13.5 the install portion of `nest new` fails because of the `strict-peer-dependencies` option being set inherently to `true`, as we do not add every peer dependency to the `package.json`
Issue Number: #1806
`nest new` …

fix: update pnpm install flags

---

lib/compiler/plugins-loader.ts

```
[ ] Bugfix
[ ] Feature
```
The method `isObject` is deprecated (see screenshot)
```
[ ] Yes
[x] No
```
PR to be evaluated

chore(): remove method deprecated 

---

commands/start.command.ts

```
[ ] Bugfix
[x] Feature
```
Before this `start` command was not able to pass additional arguments to `<app>`
Issue Number: #1844
You can now pass additional arguments to `<app>` after the `--` argument.
```
[ ] Yes
[x] No
```

feat: Allow passing arguments to nest start <app>

---

actions/build.action.ts
lib/compiler/assets-manager.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/nestjs/nest-cli/issues/1828
Will copy all the assets configured on build.
```
[ ] Yes
[x] No
```

fix(): copy all assets on build

---

actions/new.action.ts
commands/new.command.ts

(it is #1585 but now I'm trying to participate on Hacktoberfest 2022 haha)
```
[x] Bugfix
[ ] Feature
```
Issue Number: fixes https://github.com/nestjs/schematics/issues/249 (and closes #500)
<details><summary>demo</summary>
https://user-images.githubusercontent.com/13461315/160044611-3072c698-7ad5-480b-84fb-ec6502fb89f6.mp4
</details>
The `packageManager` option on `application` schematics is defined by `-p`/`--package-manager` or by the selector prompted to the user. Using `npm` by default, as usual …

fix: package name selection for `application` schematics

---

actions/build.action.ts
lib/compiler/assets-manager.ts

Revert "fix(): copy all assets on build"

---

lib/schematics/collection.factory.ts

```
[ ] Bugfix
[ ] Feature
[] Code style update (formatting, local variables)
```
The original code used a switch statement to determine which type of AbstractCollection instance to return. The new code uses a conditional if statement to perform the same task, which makes the code more concise and readable. Additionally, the instantiation of the SchematicRunner object was moved outside of the conditional statement, so that it only needs to be created once, improving the performance of the code.
```
[ ] Yes
[x] No
```

refactor: collection-factory create method

---

actions/generate.action.ts
bin/nest.ts
commands/command.loader.ts
commands/generate.command.ts
lib/schematics/abstract.collection.ts
lib/schematics/custom.collection.ts
lib/schematics/nest.collection.ts

```
[x] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
Related:
Issue Number: #1433 
PR: #1434 
Currently, when you run `nest generate --help`, it will only display schematics from the `@nestjs/schematics` package. If you have a custom collection configured in `nest-cl.json`, it doesn't display the schematics from your custom package.
Example:
Example:
After this change, you can see which collection is being selected and a table of schematics from that collection
```
[ ] Yes
[X] No **
```
**It changes the commander to load …

fix: display custom schematics in help

---

lib/schematics/nest.collection.ts

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: tiny info message enhancement
```
Currently, schematics in help message of cli are partially ordered and it may be confused.
schematics in help message of cli are fully ordered.
```
[ ] Yes
[x] No
```

chore: sort schematics in help message

---

actions/start.action.ts
lib/compiler/helpers/get-value-or-default.ts
lib/configuration/configuration.ts
lib/configuration/defaults.ts
test/lib/compiler/helpers/get-value-or-default.spec.ts
test/lib/configuration/nest-configuration.loader.spec.ts

```
[ ] Bugfix
[x] Feature
```
Currently, I can change the default node process by giving --exec as a start command option.  
However, this can make the npm run command too long in the package.json.
So I suggest adding the `exec` option can be set also in the nest-cli.json configuration file like this PR changes.  
This can be also helpful for monorepo project if each of the apps that has different execution behavior.
In my case, I use a lot of --exec option in my package.json:  
```
"scripts": { …
```

feat: exec in configuration

---

lib/compiler/helpers/manual-restart.ts
lib/compiler/watch-compiler.ts

```
[ ] Bugfix
[X] Feature
```
Unable to restart watch mode manually.
Issue Number: #997
Able to manually restart watch mode (only for Typescript, not Webpack).
```
[ ] Yes
[X] No
```
I was able to successfully implement the `rs` "command" for the Typescript watch compiler. I've created a simple helper `listenForManualRestart` so it could also be plugged into the Webpack watch compiler.
Unfortunately regarding Webpack, although I was able to invalidate/close the Webpack watch process using the Node …

feat: implement manual restart for ts watchmode

---

actions/generate.action.ts
commands/generate.command.ts
lib/configuration/configuration.ts
lib/schematics/custom.collection.ts
lib/utils/project-utils.ts

```
[ ] Bugfix
[x] Feature
```
currently, a generated spec file always ends with `.spec.ts`
Issue Number: #1683 
There should be a cli flag and config option to specify the suffix to be used, with the default being spec.
nest g res foo --spec-file-suffix=test
nest-cli.json:
{
"generateOptions": {
"spec": true,
"specFileSuffix": "test"
}
}
```
[ ] Yes
[x] No
```

feat: added new generate option to control spec file name

---

lib/configuration/nest-configuration.loader.ts
test/lib/configuration/nest-configuration.loader.spec.ts

```
[ ] Bugfix
[x] Feature
```
I believe that the most common name for nestjs CLI config file is `nest-cli.json`. Still, it is the last one being looked up when loading the config file over 3 others patterns.
I can't tell if this is the desired behavior as it is not documented.
The file `nest-cli.json` is now the first one to be selected among all the others names which are:
- `.nestcli.json`
- `nest-cli.json`
- `nest.json`
```
[x] Yes
[ ] No
```
for instance, people might be using a private/local …

perf(lib)!: prioritize 'nest-cli.json' file over all the others name patterns

---

actions/build.action.ts
lib/compiler/webpack-compiler.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: closes #2039
when the `--entryFile` CLI option is supplied, it will be used by webpack compiler
```
[ ] Yes
[x] No
```

fix: load the entry file supplied via command-line option

---

lib/compiler/watch-compiler.ts
lib/configuration/configuration.ts
lib/configuration/defaults.ts
test/lib/configuration/nest-configuration.loader.spec.ts

```
[ ] Bugfix
[x] Feature
```
When running the REPL, the server interferes with the REPL especially when running REPL from within a docker container.
This is implemented in Nodemon: https://github.com/remy/nodemon/blob/main/faq.md#nodemon-doesnt-work-with-my-repl
Allow manual restart to be disabled, this will prevent nest from listening to STDIN and allow REPL to take over.
```
[ ] Yes
[x] No
```

feat: allow disabling manual restart for ts watchmode

---

actions/add.action.ts
actions/build.action.ts
actions/new.action.ts
commands/generate.command.ts
commands/new.command.ts
lib/compiler/helpers/get-value-or-default.ts
lib/package-managers/package-manager.factory.ts
lib/readers/file-system.reader.ts
lib/schematics/collection.factory.ts
lib/utils/project-utils.ts
test/lib/package-managers/package-manager.factory.spec.ts
test/lib/package-managers/pnpm.package-manager.spec.ts
test/lib/readers/file-system.reader.spec.ts

```
[ ] Bugfix
[ ] Feature
```
- there are few places where the callback version of native nodejs modules are used
- I found one place in which a string concatenation for file path was used when we could use the cross-platform version
- replace those calls of `fs.` with their Promise-based API since they were introduced in nodejs v10.0.0
- replace `"${foo}/${bar}"` with `path.join(foo, bar)` for cross-platform compatibility sake
- add unit tests for `PackageManagerFactory.find`
- run `npm run format` …

refactor: use native fs promise-based API instead of promisify & fix formatting

---

lib/compiler/defaults/swc-defaults.ts

```
[x] Bugfix
[ ] Feature
```
SWC adopts ESNext behaviour of explicitly setting fields as `undefined` by default. Disabling this behaviour aligns better with TS that targets ES2021.
The result is as following:
```ts
import { plainToInstance } from "class-transformer";
class SomeClass {
public aNumber: number;
public aString: string;
}
const partialA = plainToInstance(SomeClass, { aNumber: 1 });
const partialB = plainToInstance(SomeClass, { aString: "abc" });
console.log({ ...partialA, ...partialB }); …
```

fix(swc): don't set missing class fields

---

lib/utils/remaining-flags.ts

```
[x] Bugfix
[ ] Feature
```
`nest start --exec "node --experimental-specifier-resolution=node --no-warnings" --debug` fails with `TypeError: Cannot read properties of undefined (reading 'toUpperCase')`, because the `camelCase` function gets `"de experimental-specifier-resolution=node --no-warnings"` as input. splitting `--` will result in an empty string, and `''[0]` is undefined.
It doesn't break.
```
[ ] Yes
[x] No
```
Alternatives might be to skip all `item` values that don't start with '--' or …

fix getRemainingFlags for arguments with multiple '--' in them

---

.eslintignore
actions/build.action.ts

```
[ ] Bugfix
[x] Feature
```
since v10, if we use nodejs v14, we run the `build` command because of `path/posix` nodejs package, which is used in the newly added `swc` compiler integration  
Although expected, I found a bit odd that the swc compiler files are loaded even tho we are using `tsc`/`webpack` as they are not supposed to be used together
lazily loads few files required for the compiler being used on `build` and `start` commands, which decreases the build time a bit
```
[ ] Yes
[x] No
```

perf(actions): only load the files of the used compiler on running `build` or `start` commands

---

actions/build.action.ts
commands/build.command.ts
commands/start.command.ts
lib/compiler/defaults/swc-defaults.ts
lib/compiler/watch-compiler.ts
lib/runners/abstract.runner.ts
lib/schematics/abstract.collection.ts
lib/schematics/schematic.option.ts

```
[x] Bugfix
[x] Feature
```
Issue Number: closes #2205
- feat: support `nest build --watch --preserveWatchOutput`
- fix: use `preserveWatchOutput` option from the tsconfig file loaded by the CLI if the flag `--preserveWatchOutput` was not supplied
```
[ ] Yes
[x] No
```

feat: add `--preserveWatchOutput` to 'build' command and support using this option from tsconfig file

---

lib/compiler/swc/swc-compiler.ts
test/lib/compiler/swc/swc-compiler.spec.ts

```
[x] Bugfix
[ ] Feature
```
If SWC is used as a compiler and the --watchAssets parameter is set, the application never quits after the command has been executed.
When you execute `pnpm run start:cli:swc`, the application never shuts down.
https://github.com/thomasync/swc-nestjs-compilation/tree/clear-watchers-never-called
Now when you execute `pnpm run start:cli:swc`, the application exits correctly. 
https://github.com/thomasync/swc-nestjs-compilation/tree/clear-watchers-never-called-fixed
```
[ ] …
```

fix(swc): should clear watchers if we are not in watch mode, and refact

---

commands/start.command.ts

Commander requires an explicit call to `allowUnknownOption` to allow and not error on options it does not recognize. This causes an issue with [this functionality](https://github.com/nestjs/nest-cli/pull/1847) because any user-defined flags are blocked at the command level.
```
[x] Bugfix
[ ] Feature
```
This is a proposal for a fix to restore the behavior of forwarding flags on to the `nest start` command. Currently, commander fails any calls with `--xxxx` flags it doesn't recognize, so that …

fix(cli): Update start.command.ts to allowUnknownOption

---

actions/start.action.ts

```
[x] Bugfix
[ ] Feature
```
The `start` command breaks when `nest start` is executed with bun (`bunx nest start`). This is because Node supports running a file w/o an extension (`node /path/to/dist/main`) but Bun requires an extension.
Per https://github.com/nestjs/nest-cli/pull/2223
This uses `require.resolve` to resolve the entrypoint to an absolute file path before starting the child process. 
Before: `/Users/colinmcd94/Documents/repos/nest-cli/nest-app/dist/main`
After: …

fix: Resolve absolute path for `start` action

---

lib/compiler/swc/swc-compiler.ts
test/lib/compiler/swc/swc-compiler.spec.ts

This is an implicit bugfix.
```
[x] Bugfix
[ ] Feature
```
`@nest/cli` does not resolve `jsc.baseUrl` even though it reads `jsc.baseUrl` from `.swcrc`.
See https://github.com/swc-project/swc/pull/7827 for the reason that `@swc/core` cannot resolve `jsc.baseUrl` if it's not coming from `.swcrc`
It's resolved from the directory of `.swcrc`, if exists, and the project root (I guess?) if not.
```
[ ] Yes
[x] No
```
I'm author of the SWC project

fix(cli): Resolve `jsc.baseUrl` before calling `@swc/cli`

---

lib/compiler/defaults/swc-defaults.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat: swc currently support paths mapping on Windows

---

lib/configuration/nest-configuration.loader.ts

```
[ ] Bugfix
[ ] Feature
```
Issue Number: closes #2275 
now `#load` is being invoked only once instead of twice (`generate.command`, `build.action`) when running `nest build`. And only once instead of three times (`generate.command`, `start.action`, `build.action`) on `nest start`
The downside of this solution is that there's no way to bypass the cache. So a command cannot access a fresh version of the config file unless the CLI process restarts. But AFAIK (and tested) this isn't a feature of the …

perf: cache loaded configuration file

---

actions/start.action.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: #2242 
The spawn command takes an array of strings, which are no longer escaped and passes them through like this:
```
/Users/me/.local/share/nvm/v18.16.1/bin/node /Users/me/app/dist/main.js json-command --json {"foo": "bar"}
```
All arguments are passed through quoted so the `spawn` command runs this instead:
```
/Users/me/.local/share/nvm/v18.16.1/bin/node /Users/me/app/dist/main.js "json-command" "--json" "{\\"foo\\": \\"bar\\"}"
```
```
[ ] Yes
[ ] No …
```

fix: Prevent need for double escaping strings

---

package.json

```
[ ] Bugfix
[ ] Feature
```
This commit addresses a dependency compatibility issue in the `@nestjs/cli` npm module. 
The `engine` field in the `package.json` has been updated to align with the minimum Node.js version requirement ("14 || >=16.14") specified by the `lru-cache` module (version ^9.0.0), an indirect dependency via `path-scurry`.
This change ensures that the `@nestjs/cli`'s Node.js version requirement remains consistent throughout its dependency chain, thereby preventing potential …

chore: update Node.js minimum version requirement

---

lib/compiler/assets-manager.ts
package-lock.json
package.json

```
[x] Bugfix
[ ] Feature
```
Even if watchAssets flag is false, the  running `nest start` process can't exit from entry file because chokidar watches files and entry script runs as another child process when using  webpack.
The reason why is internal `runWebpack` method doesn't call `assetsManager.closeWatchers()` when using `nest start`, but  `nest build` does. At first, simply I tried to call `assetsManager.closeWatchers()` after onSuccess in compiler/webpack but, it can't listen to complete all …

Synchronously copy files when watchAssets: false

---

actions/info.action.ts
lib/ui/messages.ts
test/actions/info.action.spec.ts

More details here: https://github.com/nestjs/nest-cli/issues/1929
There is no warnin message if deveopers use different version of the nest-js package in a projet
Issue Number: https://github.com/nestjs/nest-cli/issues/1929
Developer now gets a warning message folowing the suggestion => https://github.com/nestjs/nest-cli/issues/1929

feat: add warning message for the info command

---

lib/compiler/assets-manager.ts
lib/configuration/nest-configuration.loader.ts
lib/readers/file-system.reader.ts
lib/readers/reader.ts
test/lib/configuration/nest-configuration.loader.spec.ts
test/lib/readers/file-system.reader.spec.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: closes #2434
exit with an error. See:
https://github.com/nestjs/nest-cli/assets/13461315/2aad7161-08d9-4c56-a2c4-392a04203833
We got the same output for `nest generate` command
```
[ ] Yes
[x] No
```

fix: exit with an error when some config file was found but lacks on reading permissions

---

lib/compiler/assets-manager.ts

I checked the Test checkbox because I couldn't find a way to test for it.
```
[x] Bugfix
[ ] Feature
```
This pull request addresses the issues encountered with the Nest CLI assets property on Windows platforms (#2397 and #2429), specifically related to the path format causing file copying to fail. The modifications ensure compatibility across different operating systems and correct the handling of Windows path formats.
```
[ ] Yes
[x] No
```

Fix assets copying

---

lib/compiler/swc/swc-compiler.ts

```
[ ] Bugfix
[x] Feature
```
`npm i` isn't supposed to be used when we're using another package manager. So this can be confusing to new nodejs devs out there.
- no hint on which command we should run to fix the error because it's misleading
- Follows the same wording as the errors raised by `@nestjs/common`
```
[ ] Yes
[x] No
```

feat: less verbose 'missing packages' error message

---

actions/start.action.ts
package-lock.json
package.json

```
[ ] Bugfix
[x] Feature
```
Issue Number: closes #2629
- uses [`--enable-source-maps`](https://nodejs.org/docs/latest-v16.x/api/cli.html#--enable-source-maps) nodejs flag instead of the `source-map-support` 3rd-party package
- fix the `clean` npm-script 
```
[ ] Yes
[x] No
```

feat: replace 'source-map-support' with nodejs native source mapping binding

---

actions/build.action.ts
lib/compiler/assets-manager.ts
lib/utils/is-module-available.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: closes #2421
propagate any errors raised when loading the webpack configuration file. For example:
<details>
<summary>1. when webpack config path is not supplied but the file do exists</summary>
in this case I didn't installed `run-script-webpack-plugin` and the config file is using it
</details>
<details>
<summary>2. when the supplied webpack config path is not found</summary>
</details>
```
[ ] Yes
[x] No(?)
```

fix: propagate errors raised when loading the webpack configuration file

---

lib/compiler/helpers/copy-path-resolve.ts

```
[x] Bugfix
[ ] Feature
```
The nestjs build fails when addeing a single file asset item to copy a config file from the nestjs root directory.
https://github.com/nestjs/nest-cli/issues/2677
Issue Number: 2677
The build allows copying files the project root directory.
```
[ ] Yes
[x] No
```

fix: allow resolving copy paths for files in project root folder

---

actions/generate.action.ts
lib/configuration/configuration.ts

```
[ ] Bugfix
[x] Feature
```
Issue Number: [#1849](https://github.com/nestjs/nest-cli/issues/1849)
Added a new option "baseDir". With this new option, new files related to this directory will be created and imported to the app module.
```
[ ] Yes
[x] No

feat: basedir option added to configuration for generate command

---

lib/compiler/assets-manager.ts

`chokidar.watch` listen also for hidden files but `glob` do not. This means hidden files are copied in watch mode but they are not when watch mode is turned off
```
[x] Bugfix
[ ] Feature
```
Hidden files are not coppied when watch mode is turned off
Issue Number: #2653
Hidden files will be copied regardless watch mode
```
[ ] Yes
[x] No
```

fix: unification copy behavior between watched and not watched assets

---

actions/build.action.ts
commands/build.command.ts
commands/start.command.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: #2791
```
[ ] Yes
[x] No
```

fix: show type check warning only when builder is not swc 

---

actions/build.action.ts
commands/build.command.ts
lib/compiler/assets-manager.ts
lib/compiler/compiler.ts
lib/compiler/helpers/delete-out-dir.ts
lib/compiler/helpers/get-builder.ts
lib/compiler/helpers/get-tsc-config.path.ts
lib/compiler/helpers/get-webpack-config-path.ts
lib/compiler/swc/swc-compiler.ts
lib/compiler/watch-compiler.ts
lib/compiler/webpack-compiler.ts

(checking the tests box since I don't see a way to add "high-level" tests for an `Action`, only for stuff in `/lib`)
(docs == `commander` option descriptions)
```
[ ] Bugfix
[x] Feature
```
Issue Number: #2026
- added an `--all` flag to `nest build` to build all projects in a monorepo
- as a bonus: added an ability to specify several projects as `nest build` args (the `--all` flag was easier to implement this way :)
```
[ ] Yes
[x] No
```

#2026 feat: nest build --all flag

---

lib/schematics/custom.collection.ts
test/jest-config.json
test/lib/schematics/custom.collection.spec.ts
test/lib/schematics/fixtures/extended/collection.json
test/lib/schematics/fixtures/package/a/b/c/collection.json
test/lib/schematics/fixtures/package/package.json
test/lib/schematics/fixtures/simple/collection.json

```
[ ] Bugfix
[x] Feature
```
The CLI lists available schematics from custom collections by parsing the `collection.json` file directly. This list does not include schematics that may be available via an `extends` key in the `collection.json`. It also looks for `collection.json` in a fixed location, rather than supporting the `schematics` key of `package.json`.
The CLI lists *all* available schematics (with `extends` support) and locates the `collection.json` using the `schematics` …

feat(schematics): list schematics from extended collections

---

actions/start.action.ts
commands/start.command.ts

When running on Linux/WSL, `nest start --watch` does not wait the app to shutdown on restart. That leads to two instances of application running simultaneously, especially if it has async shutdown hooks. That commit fixes that adding an option to disable shell mode when spawning child processes so then app will completely shutdown first and only then started again. Thanks @jleverenz for the investigation and solution idea in [#1641](https://github.com/nestjs/nest-cli/issues/1614#issuecomment-1463838659)
fixes nestjs/nest-cli/1614
```
[ ] Bugfix
[x] Feature
[ ] Build related …
```

feat: add flag to disable shell mode for `nest start --watch`

---

actions/start.action.ts
commands/start.command.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```

feat: add support for --env-file flag

---

actions/add.action.ts
actions/build.action.ts
actions/generate.action.ts
actions/info.action.ts
actions/new.action.ts
actions/start.action.ts
commands/command.loader.ts
commands/generate.command.ts
lib/compiler/helpers/manual-restart.ts
lib/compiler/swc/constants.ts
lib/compiler/swc/swc-compiler.ts
lib/compiler/swc/type-checker-host.ts
lib/package-managers/abstract.package-manager.ts
lib/runners/abstract.runner.ts
lib/runners/runner.factory.ts
lib/ui/messages.ts
lib/ui/prefixes.ts
package-lock.json
package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
This PR replaces the outdated [chalk@4](https://www.npmjs.com/package/chalk/v/4.1.2) (`64 kB` install size, 2 dependencies) package with smaller and faster [ansis](https://github.com/webdiscus/ansis).
- ansis is compatible with chalk API, plus supports [named import](https://github.com/webdiscus/ansis#named-import):  `import { red,  bold, bgRgb } from 'ansis'`
- Installed package size only `10KB` (no dependencies), see [Compare the …

refactor: replace chalk with smaller and faster ansis

---

lib/ui/messages.ts

When using `nest new <projectname>` a message shows up like this:
`Which package manager would you ❤️to use?`
Adding a space makes it more consistent with the other messages in the file, where a double space after the emoji is already present.

style: adjust spacing after heart emoji in package_manager_question

---

actions/generate.action.ts
actions/new.action.ts
actions/start.action.ts
commands/command.input.ts
commands/start.command.ts
lib/utils/type-assertions.ts

```
[ ] Bugfix
[x] Feature
```
Issue Number: closes #2981
just like nodejs's `--env-file` feature, Nest CLI will support supplying multiple `--env-file` arguments  
```
[ ] Yes
[x] No
```

feat: support multiple `--env-file` arguments
