nestjs/nest-cli

- .npmignore
- package-lock.json
- package.json
- scripts/clean-script.ts
- scripts/clean.script.ts
- scripts/copy.script.ts
- scripts/lib/clean.ts
- scripts/lib/copy.ts
- scripts/lib/tests/clean.spec.ts
- scripts/lib/tests/copy.spec.ts
- scripts/tsconfig.json
- src/core/assets/module-finders/tests/module.finder.spec.ts
- src/core/assets/module-path-solver/module.path-solver.ts
- src/core/assets/module-path-solver/tests/module.path-solver.spec.ts
- src/core/utils/string.utils.ts
- src/core/utils/tests/file-system.utils.spec.ts
- src/core/utils/tests/path.utils.spec.ts
- src/core/utils/tests/string.utils.spec.ts
- Need to develop scripts to install properly the project
- Need to review some path manipulations to be cross platform
> Issue 8: Problem with windows users

- src/assets/ts/pipe/pipe.ts.template
> fixes #21 - fix error PipeTransform<T> require 1 arguments

- README.md
Add entry file property to nest cli config.
> Update readme for Serve command

- src/core/assets/streams/metadata.transform.ts
resolve error when generating a module that contains assets with es6 spread
> to close #37 error generating module with es6 spread

- package-lock.json
- package.json
- src/commands/generate/asset.emitter.ts
- src/commands/generate/asset.generator.ts
- src/commands/generate/handler.ts
- src/commands/generate/module-import.register.ts
- src/commands/generate/module-metadata.parser.ts
- src/commands/generate/module-metadata.register.ts
- src/commands/generate/module.emitter.ts
- src/commands/generate/module.loader.ts
- src/commands/generate/module.register.ts
- src/commands/generate/tests/module-metadata.parser.spec.ts
- src/utils/file-system.utils.ts
fix #48 [BUG] generate not working
> generate : fix issue #48

- package-lock.json
- src/commands/info/handler.ts
- src/commands/info/tests/handler.spec.ts
> Revert "issue #50"

- src/index.ts
> [Fix] correct semantic error in warning message

- commands/generate.js
Unable to execute generate command after schematic input check
fix #80
> fix(5.0.0) : generate command broken

- .dockerignore
- package-lock.json
- package.json
fix #90 docs(npm): no readme displayed on npm.org
> CLI v4 documentation

- .dockerignore
- package-lock.json
- package.json
fix #90 docs(npm): no readme displayed on npm.org
> CLI v5 documentation

- Dockerfile
- commands/generate.command.ts
- lib/schematics/abstract.collection.ts
- lib/schematics/nest.collection.ts
- lib/schematics/schematic.option.ts
- package-lock.json
- package.json
- test/jest-config.json
- test/lib/schematics/nest.collection.spec.ts
- test/lib/schematics/schematic.option.spec.ts
> refactor(dept) : increase nest cli

- lib/schematics/schematic.option.ts
- test/lib/schematics/schematic.option.spec.ts
> fix() : better schematic option management on new and generate commands

- actions/add.action.ts
- commands/add.command.ts
- commands/command.loader.ts
- lib/package-managers/abstract.package-manager.ts
> feature(add) : develop add dependency command

- actions/generate.action.ts
- lib/configuration/configuration.ts
- lib/configuration/defaults.ts
- lib/configuration/nest-configuration.loader.ts
- lib/dependency-managers/nest.dependency-manager.ts
- package.json
- test/lib/configuration/nest-configuration.loader.spec.ts
and support `nest-cli.json` + `nest.json`
> feature: add sourceRoot option

- bin/nest.ts
- package-lock.json
Closes #218
> Firing in `nest` without any arguments doesn't show up any sort of prompts.
Shows up help if the user fires in `nest` without supplying any arguments.
> Show up help if no arguments supplied 

- actions/new.action.ts
- commands/new.command.ts
In response to the #232 request, we're providing the user the option to skip git initialization.
> Add a flag and check to skip git repository initialization.

- commands/generate.command.ts
- package.json
> chore(deps): change unmantained vulnerable cli table2 to cli table 3

- actions/new.action.ts
- lib/configuration/defaults.ts
Hi! 
This is supposed to address #227 :ok_hand: 
Please let me know if any changes are required :+1: !
Thanks for the great work.
> fix(#227): add a default .gitignore

- README.md
- Removed the `--rm` part
- Updated the `pwd` command for the volume mount
- Removed the `/` and replaced it with `:`
> Updated the docker command to avoid errors

- bin/nest.ts
> chore: fixup usage info

- .github/PULL_REQUEST_TEMPLATE.md
This PR adds a PULL_REQUEST_TEMPLATE. Changes are welcome 😁
> Creates a PULL_REQUEST_TEMPLATE template

- test/lib/readers/file-system.reader.spec.ts
This PR adds tests cases for the `filesystem.reader` file and introduces a little bit of refactoring in the previous tests
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Testing
```
```
[ ] Yes
[x] No
```
> Writes additional test for the filesystem reader

- lib/compiler/plugins-loader.ts
Plugins are loaded via node's require mechanisms, instead of a plain file call, allowing control of main file to be delegated to package, as well as support any format supported by the running node version (js, mjs, etc.)
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
Related to nestjs/swagger#490
> refactor(plugins) Plugins are loaded via node's require mechanisms

- commands/generate.command.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
Just adding missing `-d` alias for `generate` command ;)
> fix generate dry run alias

- actions/add.action.ts
- actions/build.action.ts
- actions/generate.action.ts
- actions/info.action.ts
- actions/new.action.ts
- actions/start.action.ts
- commands/command.loader.ts
- lib/package-managers/abstract.package-manager.ts
- lib/runners/abstract.runner.ts
- lib/runners/runner.factory.ts
- lib/ui/messages.ts
- lib/ui/prefixes.ts
- package-lock.json
- package.json
Updated the chalk package to the latest version
```
[x] Bugfix
[ ] Feature
```
I have two apps currently in production deployed via GitHub actions, about 7 hours ago, my apps won't be deployed because of chalk package (see screenshot). I have tried to add a resolution into my package.jsom file and still doesn't work, I also cannot my project, also updated to the `next` version which gives same result.
```
[ ] Yes
[x] No
```
> chore(): update chalk version

- actions/build.action.ts
- lib/compiler/webpack-compiler.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #608
```
[ ] Yes
[x] No
```
> fix(): resolve `yarn build` with assets hangs

- commands/generate.command.ts
- lib/schematics/nest.collection.ts
- package-lock.json
- package.json
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat: Add console command description

- README.md
```
[ ] Bugfix
[ ] Feature
```
N/A
```
[ ] Yes
[x] No
```
This PR, added license on readme
> docs(readme): added license on readme

- .npmignore
```
[ ] Bugfix
[ ] Feature
```
N/A
```
[ ] Yes
[x] No
```
This PR, removed the tslint.json file from .npmignore as the file no longer exists after migrating to eslint.
> chore(npmignore): remove file tslint.json

- package-lock.json
- package.json
> Revert "fix(deps): update dependency @nestjs/schematics to v7.3.1"

- actions/generate.action.ts
- commands/generate.command.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #954 
Following order of collection resolving: command --collection option -> config collection -> fallback
```
[ ] Yes
[x] No
```
> fix(): custom collection in config

- lib/compiler/webpack-compiler.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: 1318
https://github.com/nestjs/nest-cli/issues/1318
See issue
```
[ ] Yes
[x] No
```
> feat(watch mode): toggle webpack development mode on watch

- .eslintrc.js
- lib/utils/project-utils.ts
- lib/utils/tree-kill.ts
- tsconfig.json
> style(eslint): fix eslint errors and configuration

- commands/generate.command.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #1433
a minor change that could prevent misusages
```
[ ] Yes
[x] No
```
> refactor: clarify about schematics available on generate command

- lib/compiler/hooks/tsconfig-paths.hook.ts
- test/lib/compiler/hooks/__snapshots__/tsconfig-paths.hook.spec.ts.snap
- test/lib/compiler/hooks/fixtures/type-imports/src/main.ts
- test/lib/compiler/hooks/fixtures/type-imports/src/type-a.ts
- test/lib/compiler/hooks/fixtures/type-imports/src/type-b.ts
- test/lib/compiler/hooks/fixtures/type-imports/src/type-c.ts
- test/lib/compiler/hooks/fixtures/type-imports/src/type-d.ts
- test/lib/compiler/hooks/fixtures/unused-imports/src/bar.ts
- test/lib/compiler/hooks/fixtures/unused-imports/src/foo.ts
- test/lib/compiler/hooks/fixtures/unused-imports/src/main.ts
- test/lib/compiler/hooks/tsconfig-paths.hook.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1406
result code not have unused imports and type import now
```
[ ] Yes
[x] No
```
with test file add
> fix: set flags from old node

- LICENSE
update for 2022
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: License Writing
```
N/A
N/A
```
[ ] Yes
[x] No
```
> chore(license): update for 2022

- actions/new.action.ts
- lib/package-managers/abstract.package-manager.ts
- lib/schematics/schematic.option.ts
- lib/utils/formatting.ts
- test/lib/schematics/schematic.option.spec.ts
```
[X] Bugfix
[ ] Feature
```
Currently underscores are turned into dashes.
Issue Number: https://github.com/nestjs/nest-cli/issues/489
Underscores are supported from nest-cli.
The commands built are with underscores, however, this will not fix the issue entirely since it must also be changed here:
https://github.com/nestjs/schematics/blob/2c732fb2718d7b33adfe64415d315aceee497c44/src/lib/controller/controller.factory.ts#L49
If the PR is accepted I will also make the PR in the other repo.
```
[ ] Yes …
```
> fix(options): allow underscore in names

- commands/generate.command.ts
```
[X] Bugfix
[X] Feature
```
Issue Number: https://github.com/nestjs/schematics/issues/958
new flag is added ```--no-flat``` which allows gateways, classes and a bunch of other schematics to also generate a dir.
More info here: https://github.com/nestjs/schematics/issues/958#issuecomment-1049026418
Result after the PR:
```
npm run build && node bin/nest.js g gateway a12/b --dry-run --no-flat
> @nestjs/cli@8.2.1 build
> tsc
? Which project would you like to generate to? src [ Default ]
CREATE src/a12/b/b.gateway.spec.ts (425 bytes)
CREATE src/a12/b/b.gateway.ts (235 bytes)
Dry run enabled. No files written to disk.
```
```
npm run build && node bin/nest.js g gateway a12/b --dry-run
> …
```
> feat: allow no-flat configuration via args

- actions/add.action.ts
- actions/build.action.ts
- commands/add.command.ts
```
[X] Bugfix
```
Failure to add:
Failure on `add` doesn't return a non zero exit code
```
npm run build && node bin/nest.js add asd ; echo $?
> @nestjs/cli@8.2.1 build
> tsc
▹▸▹▹▹ Package installation in progress... ☕
Failed to execute command: npm install --save asd@latest
✖ Package installation in progress... ☕
Unable to install library asd because package did not install. Please check package name.
0
```
Issue Number:
It has to do with https://github.com/nestjs/nest-cli/issues/1564 but does not adress the specific issues it has there.
add fails with a non zero exit code
```
npm run build && node bin/nest.js add asd ; echo $?
> @nestjs/cli@8.2.1 build
> tsc
▹▸▹▹▹ Package …
```
> fix: fail on nest add results in non 0 exit code

- README.md
```
[ ] Bugfix
[ ] Feature
```
Update logo 
```
[ ] Yes
[x] No
```
Update logo readme ( A small and quick update 😁)
P.s. however, joking and laughing, only the logo gives a different and very beautiful vision. 😻
> docs(readme): update logo

- README.md
Updated some details in README file
> doc: Update ReadME

- actions/add.action.ts
- commands/add.command.ts
- lib/utils/project-utils.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: 1809
Allows the use of skip-install option flag for add actions
```
[ ] Yes
[x] No
```
No current convention exists within this repository for unit testing actions/commands.
Availability of flag should be updated in general docs.
> feat(cli): allow skip-install for add

- .circleci/config.yml
```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
Many pull requests to update dependencies is failed to build caused by Node.js version mismatch.
https://app.circleci.com/pipelines/github/nestjs/nest-cli/3992/workflows/c0aeabe3-38aa-46d6-9921-404cc7429348/jobs/7608
```
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: npm@9.1.2
npm ERR! notsup Not …
```
> ci: use nodejs v18

- lib/compiler/plugins-loader.ts
> Revert "chore(): remove method deprecated "

- LICENSE
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: License
```
```
[ ] Yes
[x] No
```
> chore(license): Update to 2023

- lib/compiler/watch-compiler.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/nestjs/nest-cli/issues/1878
```
[ ] Yes
[x] No
```
> fix(watch-compiler): merge compiler options with config file options

- actions/build.action.ts
Hey there :)
There is a duplicated type in `./actions/build.action.ts:166`.
I don't think tests nor docs are needed here. Please correct me if I'm wrong.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> Remove duplicated type

- lib/compiler/defaults/swc-defaults.ts
- lib/compiler/swc/swc-compiler.ts
- lib/configuration/configuration.ts
```
[x] Bugfix
[x] Feature
```
Issue Number: #2138  #2139 
- Fix SWC builder not set `sourceRoot` to SWC filenames
- feat: Allow custom output dir readable from `tsconfig.json`
```
[ ] Yes
[x] No
```
> feat(swc): Allow custom configuration of SWC CLI options in `nest-cli.json`

- lib/compiler/swc/swc-compiler.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number:  #2160
```
[ ] Yes
[x] No
```
> fix(swc): deepMerge didn't handle array type properly

- actions/start.action.ts
> Revert "fix: Resolve absolute path for `start` action"

- actions/start.action.ts
```
[x] Bugfix
[ ] Feature
```
Fixed 
```
Uncaught Error Error: Cannot find module 'source-map-support/register'
Require stack:
- internal/preload
at Module._resolveFilename (internal/modules/cjs/loader:1028:15)
at Module._load (internal/modules/cjs/loader:873:27)
at internalRequire (internal/modules/cjs/loader:169:19)
at Module._preloadModules (internal/modules/cjs/loader:1375:5)
at loadPreloadModules (internal/bootstrap/pre_execution:583:5)
at prepareMainThreadExecution …
```
> fix(cli): Cannot find module 'source-map-support/register'

- actions/start.action.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: closes #2358
```
[ ] Yes
[x] No
```
> fix: when running start on dir paths with blank spaces

- actions/info.action.ts
- lib/utils/os-info.utils.ts
- package-lock.json
- package.json
```
[x] Bugfix
[ ] Feature
```
`nest info` logs `Unknown` on newer versions of os versions which are not added yet to os-name package, while os-name is not updated frequently we can't depend on it.
Issue Number: #2400
`nest info` now logs `MacOs 23.0.0` instead of 'MacOs Sonoma' for example. …
> refactor: Implement osName, remove os-name package

- lib/compiler/defaults/swc-defaults.ts
```
[ ] Bugfix
[x] Feature
```
if tsconfig has sourcemap enabled and i don't use swcrc, the sourcemap won't be generated. 
swc will apply tsconfig sourcemap setting. 
```
[ ] Yes
[x] No
```
> Update swc-defaults.ts to apply tsconfig source map options.

- lib/configuration/defaults.ts
```
[ ] Bugfix
[ ] Feature
```
[Link to the issue
](https://github.com/nestjs/nest-cli/issues/2471)
Issue Number: 2471
Adds more files and directories to gitignore
```
[ ] Yes
[x] No
```
> Update gitignore to include more common files or folders

- actions/info.action.ts
- lib/compiler/defaults/swc-defaults.ts
- lib/utils/os-info.utils.ts
- test/actions/info.action.spec.ts
```
[x] Bugfix
[x] Feature
```
Issue Number: closes #2458
```
[ ] Yes
[x] No
```
> feat: check only the major slice on nestjs dep mismatch

- lib/configuration/nest-configuration.loader.ts
- lib/readers/file-system.reader.ts
- lib/readers/reader.ts
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
```
[ ] Yes
[x] No
```
I corrected the typo from **Persmissions** to **Permissions**.
> refactor: fix typo

- package-lock.json
- package.json
> Revert "fix(deps): update dependency typescript to v5.5.3"

- package-lock.json
- package.json
> Revert "fix(deps): update dependency glob to v11"

- lib/compiler/defaults/webpack-defaults.ts
```
[x] Bugfix
[ ] Feature
```
Build using webpack with option `externals: []` fails.
Issue Number: #2799 
Build success.
```
[ ] Yes
[x] No
```
> fix: webpack default config - IgnorePlugin

- lib/configuration/nest-configuration.loader.ts
- test/lib/configuration/nest-configuration.loader.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #2765
no longer supports the following nestjs's CLI configuration files:
- `.nestcli.json`
- `nest.json`
```
[x] Yes
[ ] No
```
> feat!: drop uncommon variants of nest cli config file name

- lib/compiler/defaults/webpack-defaults.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/nestjs/nest-cli/issues/2835
```
[ ] Yes
[x] No
```
Closes https://github.com/nestjs/nest-cli/issues/2835
> fix: add missing class-transformer/storage in lazy import list

- actions/info.action.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: closes #3039 
```
[ ] Yes
[x] No
```
> fix: add missing closing square brackets

- commands/start.command.ts
- lib/runners/abstract.runner.ts
```
[ ] Bugfix
[ ] Feature
```
`shell: true` has been deprecated
`shell` is disabled by default
```
[ ] Yes
[ ] No
```
> chore: disable shell by default
